/* Copyright (C) Rong Tao @Sylincom Beijing, 2019年 06月 14日 星期五 09:06:45 CST. */
/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef PERFORMANCEINFOGROUP_H
#define PERFORMANCEINFOGROUP_H

/*
 * function declarations 
 */
void            init_performanceInfoGroup(void);
FindVarMethod   var_performanceInfoGroup;
FindVarMethod   var_cellPerfInfoTable;

#endif                          /* PERFORMANCEINFOGROUP_H */
