/* Copyright (C) Rong Tao @Sylincom Beijing, 2019年 06月 14日 星期五 09:06:33 CST. */
/* 
 Copyright (C) Rong Tao @Beijing

 Permission is granted to copy, distribute and/or modify this document
 under the terms of the GNU Free Documentation License, Version 1.3
 or any later version published by the Free Software Foundation;
 with no Invariant Sections, no Front-Cover Texts, and no Back-Cover
 Texts. A copy of the license is included in the section entitled ‘‘GNU
 Free Documentation License’’.
   2019年 03月 14日 星期四 19:24:45 CST. 
*/
/* Copyright (C) Rong Tao @Sylincom Beijing, 2019年 03月 08日 星期五 08:10:29 CST. */
/* Copyright (C) Rong Tao @Sylincom Beijing, 2019年 03月 07日 星期四 20:28:04 CST. */
/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "fpgaAssetMsg.h"
#include "mnt_mgmt_api.h"

//#include "bord_mgmt_api.h"
//#include "bord_mgmt_set_api.h"
#include "om_common_h.h"
/*
 * fpgaAssetMsg_variables_oid:
 *   this is the top level oid that we want to register under.  This
 *   is essentially a prefix, with the suffix appearing in the
 *   variable below.
 */

oid             fpgaAssetMsg_variables_oid[] =
    { 1, 3, 6, 1, 4, 1, 12001, 1, 2, 3, 2, 1, 1 };

/*
 * variable4 fpgaAssetMsg_variables:
 *   this variable defines function callbacks and type return information 
 *   for the fpgaAssetMsg mib section 
 */

struct variable4 fpgaAssetMsg_variables[] = {
    /*
     * magic number        , variable type , ro/rw , callback fn  , L, oidsuffix 
     */
#define FPGAASSETMSGPPRODUCTTYPE		1
    {FPGAASSETMSGPPRODUCTTYPE, ASN_UNSIGNED, NETSNMP_OLDAPI_RWRITE,
     var_fpgaAssetMsg, 1, {1}},
#define FPGAASSETMSGBOARDTYPE		2
    {FPGAASSETMSGBOARDTYPE, ASN_UNSIGNED, NETSNMP_OLDAPI_RWRITE,
     var_fpgaAssetMsg, 1, {2}},
#define FPGAASSETMSGFPGASERVERNAME		3
    {FPGAASSETMSGFPGASERVERNAME, ASN_OCTET_STR, NETSNMP_OLDAPI_RWRITE,
     var_fpgaAssetMsg, 1, {3}},
#define FPGAASSETMSGFPGASERVERSN		4
    {FPGAASSETMSGFPGASERVERSN, ASN_OCTET_STR, NETSNMP_OLDAPI_RWRITE,
     var_fpgaAssetMsg, 1, {4}},
#define FPGAASSETMSGFPGASERVERVERSION		5
    {FPGAASSETMSGFPGASERVERVERSION, ASN_OCTET_STR, NETSNMP_OLDAPI_RWRITE,
     var_fpgaAssetMsg, 1, {5}},
#define FPGAASSETMSGFPGASERVERMANUFDATA		6
    {FPGAASSETMSGFPGASERVERMANUFDATA, ASN_OCTET_STR, NETSNMP_OLDAPI_RWRITE,
     var_fpgaAssetMsg, 1, {6}},

#define FPGAASSETMSGINDEX		1
    {FPGAASSETMSGINDEX, ASN_INTEGER, NETSNMP_OLDAPI_RONLY,
     var_fpgaAssetMsgTable, 3, {7, 1, 1}},
#define FPGAASSETMSGFPGAID		2
    {FPGAASSETMSGFPGAID, ASN_UNSIGNED, NETSNMP_OLDAPI_RWRITE,
     var_fpgaAssetMsgTable, 3, {7, 1, 2}},
#define FPGAASSETMSGFPGASLOT		3
    {FPGAASSETMSGFPGASLOT, ASN_UNSIGNED, NETSNMP_OLDAPI_RWRITE,
     var_fpgaAssetMsgTable, 3, {7, 1, 3}},
#define FPGAASSETMSGFPGANAME		4
    {FPGAASSETMSGFPGANAME, ASN_OCTET_STR, NETSNMP_OLDAPI_RWRITE,
     var_fpgaAssetMsgTable, 3, {7, 1, 4}},
#define FPGAASSETMSGFPGAVERSION		5
    {FPGAASSETMSGFPGAVERSION, ASN_OCTET_STR, NETSNMP_OLDAPI_RWRITE,
     var_fpgaAssetMsgTable, 3, {7, 1, 5}},
#define FPGAASSETMSGFPGASN		6
    {FPGAASSETMSGFPGASN, ASN_OCTET_STR, NETSNMP_OLDAPI_RWRITE,
     var_fpgaAssetMsgTable, 3, {7, 1, 6}},
#define FPGAASSETMSGFPGAFWVERSION		7
    {FPGAASSETMSGFPGAFWVERSION, ASN_OCTET_STR, NETSNMP_OLDAPI_RWRITE,
     var_fpgaAssetMsgTable, 3, {7, 1, 7}},
#define FPGAASSETMSGROWSTATUS		8
    {FPGAASSETMSGROWSTATUS, ASN_INTEGER, NETSNMP_OLDAPI_RWRITE,
     var_fpgaAssetMsgTable, 3, {7, 1, 8}},
};

/*
 * (L = length of the oidsuffix) 
 */


/** Initializes the fpgaAssetMsg module */
void
init_fpgaAssetMsg(void)
{

    DEBUGMSGTL(("fpgaAssetMsg", "Initializing\n"));

    /*
     * register ourselves with the agent to handle our mib tree 
     */
    REGISTER_MIB("fpgaAssetMsg", fpgaAssetMsg_variables, variable4,
                 fpgaAssetMsg_variables_oid);

    /*
     * place any other initialization junk you need here 
     */
}

/*
 * var_fpgaAssetMsg():
 *   This function is called every time the agent gets a request for
 *   a scalar variable that might be found within your mib section
 *   registered above.  It is up to you to do the right thing and
 *   return the correct value.
 *     You should also correct the value of "var_len" if necessary.
 *
 *   Please see the documentation for more information about writing
 *   module extensions, and check out the examples in the examples
 *   and mibII directories.
 */
unsigned char  *
var_fpgaAssetMsg(struct variable *vp,
                 oid * name,
                 size_t *length,
                 int exact, size_t *var_len, WriteMethod ** write_method)
{
    /*
     * variables we may use later 
     */
    static long     long_ret;
    static u_long   ulong_ret;
    static unsigned char string[SPRINT_MAX_LEN];
    static oid      objid[MAX_OID_LEN];
    static struct counter64 c64;
	static unsigned long ulVar;
	static unsigned char sName[STR_LEN_16];
	static unsigned char sSN[STR_LEN_16];	
	static unsigned char sVersion[STR_LEN_16];
	static unsigned char sData[STR_LEN_12];


    if (header_generic(vp, name, length, exact, var_len, write_method)
        == MATCH_FAILED)
        return NULL;

    /*
     * this is where we do the value assignments for the mib results.
     */
    switch (vp->magic) {
    case FPGAASSETMSGPPRODUCTTYPE:
        *write_method = write_fpgaAssetMsgpProductType;
	    long_ret= CTRL_FPGA_Device_Get_produce_type(&ulVar);
		*var_len = sizeof(ulVar);
        return (u_char *) & ulVar;
    case FPGAASSETMSGBOARDTYPE:
        *write_method = write_fpgaAssetMsgBoardType;
        long_ret= CTRL_FPGA_Device_Get_board_type(&ulVar);
	    *var_len = sizeof(ulVar);
        return (u_char *) & ulVar;
    case FPGAASSETMSGFPGASERVERNAME:
        *write_method = write_fpgaAssetMsgFpgaServerName;
		long_ret= CTRL_FPGA_Device_Get_fpga_server_name(sName,STR_LEN_16);
	    *var_len = STR_LEN_16;
        return (u_char *)sName;
    case FPGAASSETMSGFPGASERVERSN:
        *write_method = write_fpgaAssetMsgFpgaServerSn;
		long_ret= CTRL_FPGA_Device_Get_fpga_server_sn(sSN,STR_LEN_16);
	    *var_len = STR_LEN_16;
        return (u_char *)sSN;
    case FPGAASSETMSGFPGASERVERVERSION:
        *write_method = write_fpgaAssetMsgFpgaServerVersion;
		long_ret= CTRL_FPGA_Device_Get_fpga_server_version(sVersion,STR_LEN_16);
	    *var_len = STR_LEN_16;
        return (u_char *)sVersion;
    case FPGAASSETMSGFPGASERVERMANUFDATA:
        *write_method = write_fpgaAssetMsgFpgaServerManufData;
		long_ret= CTRL_FPGA_Device_Get_fpga_server_manuf_data(sData,STR_LEN_12);
	    *var_len = STR_LEN_12;
        return (u_char *)sData;
    default:
        ERROR_MSG("");
    }
    return NULL;
}

/* fpgaAssetMsgTable表索引处理数 */
long header_fpgaAssetMsgTable
(
	struct variable *vp,
	oid			 *name,
	size_t 		 *length,
	int			  exact,
	size_t 		 *var_len,
	WriteMethod	**write_method,
	long			 *plIndex
)
{
	long	ret 		= 0;
	long	lComp		= MATCH_FAILED;
	long	lIndex		= 0;
	oid	newname[MAX_OID_LEN];
				 
	memset(newname, 0x00, sizeof(newname));
	memcpy(newname, name, (*length) * sizeof(oid));
				 
	if(exact)	/* get/set	*/
	{
		ret = snmp_oid_compare(newname, vp->namelen, vp->name, vp->namelen);
		if((ret == 0) && (*length == (vp->namelen + 1)))
		{
			lIndex = newname[vp->namelen];
			if((lIndex > 0) && (lIndex <= MAX_CONTRL_DEVICE_SUM)) lComp = MATCH_SUCCEEDED;
		}
	}
	else		 /* get-next */
	{
		ret = snmp_oid_compare(newname, vp->namelen, vp->name, vp->namelen);
				 
		if(ret < 0)						 /* name中的OID比注册信息中的OID靠前 */
		{
			memcpy(newname, vp->name, (vp->namelen) * sizeof(oid));
			lComp = MATCH_SUCCEEDED;
			lIndex = 1;
		}
		else if(ret == 0)
		{
		    if(*length == vp->namelen)    /* 没有带索引	*/
			{
				lComp = MATCH_SUCCEEDED;
			    lIndex = 1;
			}
			else if (*length == (vp->namelen + 1)) /* 有参照索引	 */
			{
				lIndex = newname[vp->namelen];
				lIndex += 1;
				if((lIndex > 0) && (lIndex <= MAX_CONTRL_DEVICE_SUM)) lComp = MATCH_SUCCEEDED;
			}
		}
	}
				 
		if(lComp == MATCH_SUCCEEDED)
		{
			*length  = vp->namelen + 1;
			*plIndex = lIndex;
			newname[vp->namelen] = lIndex;
			memcpy(name, newname, (*length) * sizeof(oid));
		}
				 
    return(lComp);
}


/*
 * var_fpgaAssetMsgTable():
 *   Handle this table separately from the scalar value case.
 *   The workings of this are basically the same as for var_fpgaAssetMsg above.
 */
unsigned char  *
var_fpgaAssetMsgTable(struct variable *vp,
                      oid * name,
                      size_t *length,
                      int exact,
                      size_t *var_len, WriteMethod ** write_method)
{
    /*
     * variables we may use later 
     */
    static long     long_ret;
    static u_long   ulong_ret;
    static struct counter64 c64;
	static unsigned long ulVar=0;

	static long lIndex = 0;
	static unsigned char sName[STR_LEN_16];
	static unsigned char sVersion[STR_LEN_24];
	static unsigned char sSN[STR_LEN_16];
	static unsigned char sFWVersion[STR_LEN_16];

    if (header_fpgaAssetMsgTable
        (vp,name,length,exact,var_len,write_method, &lIndex)
        == MATCH_FAILED)
        return NULL;

    switch (vp->magic) {
    case FPGAASSETMSGINDEX:
         ulVar= lIndex;    
	    *var_len = sizeof(ulVar);
        return ((unsigned char *) & ulVar);
    case FPGAASSETMSGFPGAID:
        *write_method = write_fpgaAssetMsgFpgaId;
		long_ret = CTRL_FPGA_DeviceInfo_Get_fpga_id(lIndex,&ulVar);
	    *var_len = sizeof(ulVar);	
        return (u_char *) & ulVar;
    case FPGAASSETMSGFPGASLOT:
        *write_method = write_fpgaAssetMsgFpgaSlot;
		long_ret = CTRL_FPGA_DeviveInfo_Get_fpga_slot(lIndex,&ulVar);
	    *var_len = sizeof(ulVar);	
        return (u_char *) & ulVar;
    case FPGAASSETMSGFPGANAME:
        *write_method = write_fpgaAssetMsgFpgaName;
        long_ret = CTRL_FPGA_DeviceInfo_Get_fpga_name(lIndex,sName,STR_LEN_16);
	    *var_len = STR_LEN_16;
        return (u_char *) sName;
    case FPGAASSETMSGFPGAVERSION:
        *write_method = write_fpgaAssetMsgFpgaVersion;
        long_ret = CTRL_FPGA_DeviceInfo_Get_fpga_version(lIndex,sVersion,STR_LEN_24);
	    *var_len = STR_LEN_24;
        return (u_char *) sVersion;
    case FPGAASSETMSGFPGASN:
        *write_method = write_fpgaAssetMsgFpgaSn;
        long_ret = CTRL_FPGA_DeviceInfo_Get_fpga_sn(lIndex,sSN,STR_LEN_16);
	    *var_len = STR_LEN_16;
        return (u_char *) sSN;
    case FPGAASSETMSGFPGAFWVERSION:
        *write_method = write_fpgaAssetMsgFpgaFwVersion;
        long_ret = CTRL_FPGA_DeviceInfo_Get_fpga_fw_version(lIndex,sFWVersion,STR_LEN_16);
	    *var_len = STR_LEN_16;
        return (u_char *) sFWVersion;
    case FPGAASSETMSGROWSTATUS:
        *write_method = write_fpgaAssetMsgRowStatus;
        ulVar = 0;            /* XXX */
        return (u_char *) & ulVar;
    default:
        ERROR_MSG("");
    }
    return NULL;
}



int
write_fpgaAssetMsgpProductType(int action,
                               u_char * var_val,
                               u_char var_val_type,
                               size_t var_val_len,
                               u_char * statP, oid * name, size_t name_len)
{
    u_long          value;
    int             size;

    switch (action) {
    case RESERVE1:
        if (var_val_type != ASN_UNSIGNED) {
            fprintf(stderr, "write to fpgaAssetMsg not ASN_UNSIGNED\n");
            return SNMP_ERR_WRONGTYPE;
        }
        if (var_val_len > sizeof(u_long)) {
            fprintf(stderr, "write to fpgaAssetMsg: bad length\n");
            return SNMP_ERR_WRONGLENGTH;
        }
        break;

    case RESERVE2:
        size = var_val_len;
        value = *(u_long *) var_val;

        break;

    case FREE:
        /*
         * Release any resources that have been allocated 
         */
        break;

    case ACTION:
        /*
         * The variable has been stored in 'value' for you to use,
         * and you have just been asked to do something with it.
         * Note that anything done here must be reversable in the UNDO case
         */
        break;

    case UNDO:
        /*
         * Back out any changes made in the ACTION case 
         */
        break;

    case COMMIT:
        /*
         * Things are working well, so it's now safe to make the change
         * permanently.  Make sure that anything done here can't fail!
         */
        break;
    }
    return SNMP_ERR_NOERROR;
}


int
write_fpgaAssetMsgBoardType(int action,
                            u_char * var_val,
                            u_char var_val_type,
                            size_t var_val_len,
                            u_char * statP, oid * name, size_t name_len)
{
    u_long          value;
    int             size;

    switch (action) {
    case RESERVE1:
        if (var_val_type != ASN_UNSIGNED) {
            fprintf(stderr, "write to fpgaAssetMsg not ASN_UNSIGNED\n");
            return SNMP_ERR_WRONGTYPE;
        }
        if (var_val_len > sizeof(u_long)) {
            fprintf(stderr, "write to fpgaAssetMsg: bad length\n");
            return SNMP_ERR_WRONGLENGTH;
        }
        break;

    case RESERVE2:
        size = var_val_len;
        value = *(u_long *) var_val;

        break;

    case FREE:
        /*
         * Release any resources that have been allocated 
         */
        break;

    case ACTION:
        /*
         * The variable has been stored in 'value' for you to use,
         * and you have just been asked to do something with it.
         * Note that anything done here must be reversable in the UNDO case
         */
        break;

    case UNDO:
        /*
         * Back out any changes made in the ACTION case 
         */
        break;

    case COMMIT:
        /*
         * Things are working well, so it's now safe to make the change
         * permanently.  Make sure that anything done here can't fail!
         */
        break;
    }
    return SNMP_ERR_NOERROR;
}


int
write_fpgaAssetMsgFpgaServerName(int action,
                                 u_char * var_val,
                                 u_char var_val_type,
                                 size_t var_val_len,
                                 u_char * statP,
                                 oid * name, size_t name_len)
{
    char            value;
    int             size;

    switch (action) {
    case RESERVE1:
        if (var_val_type != ASN_OCTET_STR) {
            fprintf(stderr, "write to fpgaAssetMsg not ASN_OCTET_STR\n");
            return SNMP_ERR_WRONGTYPE;
        }
        if (var_val_len > sizeof(char)) {
            fprintf(stderr, "write to fpgaAssetMsg: bad length\n");
            return SNMP_ERR_WRONGLENGTH;
        }
        break;

    case RESERVE2:
        size = var_val_len;
        value = *(char *) var_val;
        
        break;

    case FREE:
        /*
         * Release any resources that have been allocated 
         */
        break;

    case ACTION:
        /*
         * The variable has been stored in 'value' for you to use,
         * and you have just been asked to do something with it.
         * Note that anything done here must be reversable in the UNDO case
         */
        break;

    case UNDO:
        /*
         * Back out any changes made in the ACTION case 
         */
        break;

    case COMMIT:
        /*
         * Things are working well, so it's now safe to make the change
         * permanently.  Make sure that anything done here can't fail!
         */
        break;
    }
    return SNMP_ERR_NOERROR;
}


int
write_fpgaAssetMsgFpgaServerSn(int action,
                               u_char * var_val,
                               u_char var_val_type,
                               size_t var_val_len,
                               u_char * statP, oid * name, size_t name_len)
{
    char            value;
    int             size;

    switch (action) {
    case RESERVE1:
        if (var_val_type != ASN_OCTET_STR) {
            fprintf(stderr, "write to fpgaAssetMsg not ASN_OCTET_STR\n");
            return SNMP_ERR_WRONGTYPE;
        }
        if (var_val_len > sizeof(char)) {
            fprintf(stderr, "write to fpgaAssetMsg: bad length\n");
            return SNMP_ERR_WRONGLENGTH;
        }
        break;

    case RESERVE2:
        size = var_val_len;
        value = *(char *) var_val;

        break;

    case FREE:
        /*
         * Release any resources that have been allocated 
         */
        break;

    case ACTION:
        /*
         * The variable has been stored in 'value' for you to use,
         * and you have just been asked to do something with it.
         * Note that anything done here must be reversable in the UNDO case
         */
        break;

    case UNDO:
        /*
         * Back out any changes made in the ACTION case 
         */
        break;

    case COMMIT:
        /*
         * Things are working well, so it's now safe to make the change
         * permanently.  Make sure that anything done here can't fail!
         */
        break;
    }
    return SNMP_ERR_NOERROR;
}


int
write_fpgaAssetMsgFpgaServerVersion(int action,
                                    u_char * var_val,
                                    u_char var_val_type,
                                    size_t var_val_len,
                                    u_char * statP,
                                    oid * name, size_t name_len)
{
    char            value;
    int             size;

    switch (action) {
    case RESERVE1:
        if (var_val_type != ASN_OCTET_STR) {
            fprintf(stderr, "write to fpgaAssetMsg not ASN_OCTET_STR\n");
            return SNMP_ERR_WRONGTYPE;
        }
        if (var_val_len > sizeof(char)) {
            fprintf(stderr, "write to fpgaAssetMsg: bad length\n");
            return SNMP_ERR_WRONGLENGTH;
        }
        break;

    case RESERVE2:
        size = var_val_len;
        value = *(char *) var_val;

        break;

    case FREE:
        /*
         * Release any resources that have been allocated 
         */
        break;

    case ACTION:
        /*
         * The variable has been stored in 'value' for you to use,
         * and you have just been asked to do something with it.
         * Note that anything done here must be reversable in the UNDO case
         */
        break;

    case UNDO:
        /*
         * Back out any changes made in the ACTION case 
         */
        break;

    case COMMIT:
        /*
         * Things are working well, so it's now safe to make the change
         * permanently.  Make sure that anything done here can't fail!
         */
        break;
    }
    return SNMP_ERR_NOERROR;
}


int
write_fpgaAssetMsgFpgaServerManufData(int action,
                                      u_char * var_val,
                                      u_char var_val_type,
                                      size_t var_val_len,
                                      u_char * statP,
                                      oid * name, size_t name_len)
{
    char            value;
    int             size;

    switch (action) {
    case RESERVE1:
        if (var_val_type != ASN_OCTET_STR) {
            fprintf(stderr, "write to fpgaAssetMsg not ASN_OCTET_STR\n");
            return SNMP_ERR_WRONGTYPE;
        }
        if (var_val_len > sizeof(char)) {
            fprintf(stderr, "write to fpgaAssetMsg: bad length\n");
            return SNMP_ERR_WRONGLENGTH;
        }
        break;

    case RESERVE2:
        size = var_val_len;
        value = *(char *) var_val;

        break;

    case FREE:
        /*
         * Release any resources that have been allocated 
         */
        break;

    case ACTION:
        /*
         * The variable has been stored in 'value' for you to use,
         * and you have just been asked to do something with it.
         * Note that anything done here must be reversable in the UNDO case
         */
        break;

    case UNDO:
        /*
         * Back out any changes made in the ACTION case 
         */
        break;

    case COMMIT:
        /*
         * Things are working well, so it's now safe to make the change
         * permanently.  Make sure that anything done here can't fail!
         */
        break;
    }
    return SNMP_ERR_NOERROR;
}

int
write_fpgaAssetMsgFpgaId(int action,
                         u_char * var_val,
                         u_char var_val_type,
                         size_t var_val_len,
                         u_char * statP, oid * name, size_t name_len)
{
    u_long          value;
    int             size;

    switch (action) {
    case RESERVE1:
        if (var_val_type != ASN_UNSIGNED) {
            fprintf(stderr, "write to fpgaAssetMsg not ASN_UNSIGNED\n");
            return SNMP_ERR_WRONGTYPE;
        }
        if (var_val_len > sizeof(u_long)) {
            fprintf(stderr, "write to fpgaAssetMsg: bad length\n");
            return SNMP_ERR_WRONGLENGTH;
        }
        break;

    case RESERVE2:
        size = var_val_len;
        value = *(u_long *) var_val;

        break;

    case FREE:
        /*
         * Release any resources that have been allocated 
         */
        break;

    case ACTION:
        /*
         * The variable has been stored in 'value' for you to use,
         * and you have just been asked to do something with it.
         * Note that anything done here must be reversable in the UNDO case
         */
        break;

    case UNDO:
        /*
         * Back out any changes made in the ACTION case 
         */
        break;

    case COMMIT:
        /*
         * Things are working well, so it's now safe to make the change
         * permanently.  Make sure that anything done here can't fail!
         */
        break;
    }
    return SNMP_ERR_NOERROR;
}

int
write_fpgaAssetMsgFpgaSlot(int action,
                           u_char * var_val,
                           u_char var_val_type,
                           size_t var_val_len,
                           u_char * statP, oid * name, size_t name_len)
{
    u_long          value;
    int             size;

    switch (action) {
    case RESERVE1:
        if (var_val_type != ASN_UNSIGNED) {
            fprintf(stderr, "write to fpgaAssetMsg not ASN_UNSIGNED\n");
            return SNMP_ERR_WRONGTYPE;
        }
        if (var_val_len > sizeof(u_long)) {
            fprintf(stderr, "write to fpgaAssetMsg: bad length\n");
            return SNMP_ERR_WRONGLENGTH;
        }
        break;

    case RESERVE2:
        size = var_val_len;
        value = *(u_long *) var_val;

        break;

    case FREE:
        /*
         * Release any resources that have been allocated 
         */
        break;

    case ACTION:
        /*
         * The variable has been stored in 'value' for you to use,
         * and you have just been asked to do something with it.
         * Note that anything done here must be reversable in the UNDO case
         */
        break;

    case UNDO:
        /*
         * Back out any changes made in the ACTION case 
         */
        break;

    case COMMIT:
        /*
         * Things are working well, so it's now safe to make the change
         * permanently.  Make sure that anything done here can't fail!
         */
        break;
    }
    return SNMP_ERR_NOERROR;
}

int
write_fpgaAssetMsgFpgaName(int action,
                           u_char * var_val,
                           u_char var_val_type,
                           size_t var_val_len,
                           u_char * statP, oid * name, size_t name_len)
{
    char            value;
    int             size;

    switch (action) {
    case RESERVE1:
        if (var_val_type != ASN_OCTET_STR) {
            fprintf(stderr, "write to fpgaAssetMsg not ASN_OCTET_STR\n");
            return SNMP_ERR_WRONGTYPE;
        }
        if (var_val_len > sizeof(char)) {
            fprintf(stderr, "write to fpgaAssetMsg: bad length\n");
            return SNMP_ERR_WRONGLENGTH;
        }
        break;

    case RESERVE2:
        size = var_val_len;
        value = *(char *) var_val;

        break;

    case FREE:
        /*
         * Release any resources that have been allocated 
         */
        break;

    case ACTION:
        /*
         * The variable has been stored in 'value' for you to use,
         * and you have just been asked to do something with it.
         * Note that anything done here must be reversable in the UNDO case
         */
        break;

    case UNDO:
        /*
         * Back out any changes made in the ACTION case 
         */
        break;

    case COMMIT:
        /*
         * Things are working well, so it's now safe to make the change
         * permanently.  Make sure that anything done here can't fail!
         */
        break;
    }
    return SNMP_ERR_NOERROR;
}

int
write_fpgaAssetMsgFpgaVersion(int action,
                              u_char * var_val,
                              u_char var_val_type,
                              size_t var_val_len,
                              u_char * statP, oid * name, size_t name_len)
{
    char            value;
    int             size;

    switch (action) {
    case RESERVE1:
        if (var_val_type != ASN_OCTET_STR) {
            fprintf(stderr, "write to fpgaAssetMsg not ASN_OCTET_STR\n");
            return SNMP_ERR_WRONGTYPE;
        }
        if (var_val_len > sizeof(char)) {
            fprintf(stderr, "write to fpgaAssetMsg: bad length\n");
            return SNMP_ERR_WRONGLENGTH;
        }
        break;

    case RESERVE2:
        size = var_val_len;
        value = *(char *) var_val;

        break;

    case FREE:
        /*
         * Release any resources that have been allocated 
         */
        break;

    case ACTION:
        /*
         * The variable has been stored in 'value' for you to use,
         * and you have just been asked to do something with it.
         * Note that anything done here must be reversable in the UNDO case
         */
        break;

    case UNDO:
        /*
         * Back out any changes made in the ACTION case 
         */
        break;

    case COMMIT:
        /*
         * Things are working well, so it's now safe to make the change
         * permanently.  Make sure that anything done here can't fail!
         */
        break;
    }
    return SNMP_ERR_NOERROR;
}

int
write_fpgaAssetMsgFpgaSn(int action,
                         u_char * var_val,
                         u_char var_val_type,
                         size_t var_val_len,
                         u_char * statP, oid * name, size_t name_len)
{
    char            value;
    int             size;

    switch (action) {
    case RESERVE1:
        if (var_val_type != ASN_OCTET_STR) {
            fprintf(stderr, "write to fpgaAssetMsg not ASN_OCTET_STR\n");
            return SNMP_ERR_WRONGTYPE;
        }
        if (var_val_len > sizeof(char)) {
            fprintf(stderr, "write to fpgaAssetMsg: bad length\n");
            return SNMP_ERR_WRONGLENGTH;
        }
        break;

    case RESERVE2:
        size = var_val_len;
        value = *(char *) var_val;

        break;

    case FREE:
        /*
         * Release any resources that have been allocated 
         */
        break;

    case ACTION:
        /*
         * The variable has been stored in 'value' for you to use,
         * and you have just been asked to do something with it.
         * Note that anything done here must be reversable in the UNDO case
         */
        break;

    case UNDO:
        /*
         * Back out any changes made in the ACTION case 
         */
        break;

    case COMMIT:
        /*
         * Things are working well, so it's now safe to make the change
         * permanently.  Make sure that anything done here can't fail!
         */
        break;
    }
    return SNMP_ERR_NOERROR;
}

int
write_fpgaAssetMsgFpgaFwVersion(int action,
                                u_char * var_val,
                                u_char var_val_type,
                                size_t var_val_len,
                                u_char * statP,
                                oid * name, size_t name_len)
{
    char            value;
    int             size;

    switch (action) {
    case RESERVE1:
        if (var_val_type != ASN_OCTET_STR) {
            fprintf(stderr, "write to fpgaAssetMsg not ASN_OCTET_STR\n");
            return SNMP_ERR_WRONGTYPE;
        }
        if (var_val_len > sizeof(char)) {
            fprintf(stderr, "write to fpgaAssetMsg: bad length\n");
            return SNMP_ERR_WRONGLENGTH;
        }
        break;

    case RESERVE2:
        size = var_val_len;
        value = *(char *) var_val;

        break;

    case FREE:
        /*
         * Release any resources that have been allocated 
         */
        break;

    case ACTION:
        /*
         * The variable has been stored in 'value' for you to use,
         * and you have just been asked to do something with it.
         * Note that anything done here must be reversable in the UNDO case
         */
        break;

    case UNDO:
        /*
         * Back out any changes made in the ACTION case 
         */
        break;

    case COMMIT:
        /*
         * Things are working well, so it's now safe to make the change
         * permanently.  Make sure that anything done here can't fail!
         */
        break;
    }
    return SNMP_ERR_NOERROR;
}

int
write_fpgaAssetMsgRowStatus(int action,
                            u_char * var_val,
                            u_char var_val_type,
                            size_t var_val_len,
                            u_char * statP, oid * name, size_t name_len)
{
    long            value;
    int             size;

    switch (action) {
    case RESERVE1:
        if (var_val_type != ASN_INTEGER) {
            fprintf(stderr, "write to fpgaAssetMsg not ASN_INTEGER\n");
            return SNMP_ERR_WRONGTYPE;
        }
        if (var_val_len > sizeof(long)) {
            fprintf(stderr, "write to fpgaAssetMsg: bad length\n");
            return SNMP_ERR_WRONGLENGTH;
        }
        break;

    case RESERVE2:
        size = var_val_len;
        value = *(long *) var_val;

        break;

    case FREE:
        /*
         * Release any resources that have been allocated 
         */
        break;

    case ACTION:
        /*
         * The variable has been stored in 'value' for you to use,
         * and you have just been asked to do something with it.
         * Note that anything done here must be reversable in the UNDO case
         */
        break;

    case UNDO:
        /*
         * Back out any changes made in the ACTION case 
         */
        break;

    case COMMIT:
        /*
         * Things are working well, so it's now safe to make the change
         * permanently.  Make sure that anything done here can't fail!
         */
        break;
    }
    return SNMP_ERR_NOERROR;
}
