/* Copyright (C) Rong Tao @Sylincom Beijing, 2019年 06月 14日 星期五 09:06:33 CST. */
/* 
 Copyright (C) Rong Tao @Beijing

 Permission is granted to copy, distribute and/or modify this document
 under the terms of the GNU Free Documentation License, Version 1.3
 or any later version published by the Free Software Foundation;
 with no Invariant Sections, no Front-Cover Texts, and no Back-Cover
 Texts. A copy of the license is included in the section entitled ‘‘GNU
 Free Documentation License’’.
   2019年 03月 14日 星期四 19:24:45 CST. 
*/
/* Copyright (C) Rong Tao @Sylincom Beijing, 2019年 03月 08日 星期五 08:10:29 CST. */
/* Copyright (C) Rong Tao @Sylincom Beijing, 2019年 03月 07日 星期四 20:28:04 CST. */
/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "omVcmNotification.h"

extern const oid snmptrap_oid[];
extern const size_t snmptrap_oid_len;

int
send_omVcmAddResponse_trap(void *pRes)
{
	CONFIG_VCMAddState_t* pAddRes = (CONFIG_VCMAddState_t*)pRes;
	u_char ucRes = pAddRes->ucRes;
	unsigned long ulError = pAddRes->ulError_type;
    netsnmp_variable_list *var_list = NULL;
    const oid       omVcmAddResponse_oid[] =
        { 1, 3, 6, 1, 4, 1, 12001, 4, 3, 1 };
    const oid       omVcmAlarmRes_oid[] =
        { 1, 3, 6, 1, 4, 1, 12001, 2, 2, 1, 1, 3, pAddRes->ulIndex 
        };
    const oid       omVcmAlarmErrorType_oid[] =
        { 1, 3, 6, 1, 4, 1, 12001, 2, 2, 1, 1, 4, pAddRes->ulIndex
        };

    /*
     * Set the snmpTrapOid.0 value
     */
    snmp_varlist_add_variable(&var_list,
                              snmptrap_oid, snmptrap_oid_len,
                              ASN_OBJECT_ID,
                              omVcmAddResponse_oid,
                              sizeof(omVcmAddResponse_oid));

    /*
     * Add any objects from the trap definition
     */
    snmp_varlist_add_variable(&var_list,
                              omVcmAlarmRes_oid,
                              OID_LENGTH(omVcmAlarmRes_oid), ASN_INTEGER,
                              (u_char *)&ucRes, sizeof(ucRes));
    snmp_varlist_add_variable(&var_list,
                              omVcmAlarmErrorType_oid,
                              OID_LENGTH(omVcmAlarmErrorType_oid),
                              ASN_INTEGER,
                              /*
                               * Set an appropriate value for omVcmAlarmErrorType 
                               */
                              (u_char *)&ulError, sizeof(ulError));

    /*
     * Add any extra (optional) objects here
     */

    /*
     * Send the trap to the list of configured destinations
     *  and clean up
     */
    send_v2trap(var_list);
    snmp_free_varbind(var_list);

    return SNMP_ERR_NOERROR;
}

int
send_omVcmDelResponse_trap(void *pRes)
{
	CONFIG_VCMDelState_t* pDelRes = (CONFIG_VCMDelState_t*)pRes;
	u_char ucRes = pDelRes->ucRes;
	unsigned long ulError = pDelRes->ulError_type;
    netsnmp_variable_list *var_list = NULL;
    const oid       omVcmDelResponse_oid[] =
        { 1, 3, 6, 1, 4, 1, 12001, 4, 3, 2 };
    const oid       omVcmAlarmRes_oid[] =
        { 1, 3, 6, 1, 4, 1, 12001, 2, 2, 1, 1, 3, pDelRes->ulIndex 
        };
    const oid       omVcmAlarmErrorType_oid[] =
        { 1, 3, 6, 1, 4, 1, 12001, 2, 2, 1, 1, 4, pDelRes->ulIndex  
        };

    /*
     * Set the snmpTrapOid.0 value
     */
    snmp_varlist_add_variable(&var_list,
                              snmptrap_oid, snmptrap_oid_len,
                              ASN_OBJECT_ID,
                              omVcmDelResponse_oid,
                              sizeof(omVcmDelResponse_oid));

    /*
     * Add any objects from the trap definition
     */
    snmp_varlist_add_variable(&var_list,
                              omVcmAlarmRes_oid,
                              OID_LENGTH(omVcmAlarmRes_oid), ASN_INTEGER,
                              (u_char *)&ucRes, sizeof(ucRes));
    snmp_varlist_add_variable(&var_list,
                              omVcmAlarmErrorType_oid,
                              OID_LENGTH(omVcmAlarmErrorType_oid),
                              ASN_INTEGER,
                              (u_char *)&ulError, sizeof(ulError));

    /*
     * Add any extra (optional) objects here
     */

    /*
     * Send the trap to the list of configured destinations
     *  and clean up
     */
    send_v2trap(var_list);
    snmp_free_varbind(var_list);

    return SNMP_ERR_NOERROR;
}
