/* Copyright (C) Rong Tao @Sylincom Beijing, 2019年 06月 14日 星期五 09:06:32 CST. */
/* 
 Copyright (C) Rong Tao @Beijing

 Permission is granted to copy, distribute and/or modify this document
 under the terms of the GNU Free Documentation License, Version 1.3
 or any later version published by the Free Software Foundation;
 with no Invariant Sections, no Front-Cover Texts, and no Back-Cover
 Texts. A copy of the license is included in the section entitled ‘‘GNU
 Free Documentation License’’.
   2019年 03月 14日 星期四 19:24:45 CST. 
*/
/* Copyright (C) Rong Tao @Sylincom Beijing, 2019年 03月 08日 星期五 08:10:29 CST. */
/* Copyright (C) Rong Tao @Sylincom Beijing, 2019年 03月 07日 星期四 20:28:03 CST. */
/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef CPUMANAGEMSG_H
#define CPUMANAGEMSG_H
#include "sbsconfig_common.h"
#include "mnt_mgmt_api.h"
//#include "bord_mgmt_api.h"
//#include "bord_mgmt_set_api.h"
#include "om_common_h.h"
/*
 * function declarations 
 */
void            init_cpuManageMsg(void);
FindVarMethod   var_cpuManageMsg;
FindVarMethod   var_cpuAssetMsgTable;
FindVarMethod   var_cpuHealthMsgTable;
WriteMethod     write_cpuAssetMsgCpuServerId;
WriteMethod     write_cpuAssetMsgBmcId;
WriteMethod     write_cpuAssetMsgBmcName;
WriteMethod     write_cpuAssetMsgBmcFwVersion;
WriteMethod     write_cpuAssetMsgBmcAddr;
WriteMethod     write_cpuHealthMsgCpuServerId;
WriteMethod     write_cpuHealthMsgCpuServerFanThres;
WriteMethod     write_cpuHealthMsgCpuServerFan;
WriteMethod     write_computeResMsgCpuServerId;
WriteMethod     write_computeResMsgCpuUsgThres;
WriteMethod     write_computeResMsgCpuUsg;
WriteMethod     write_computeResMsgMemUsgThres;
WriteMethod     write_computeResMsgMemUsg;
WriteMethod     write_cpuAssetMsgCpuName;
WriteMethod     write_cpuAssetMsgBiosVersion;
WriteMethod     write_cpuAssetMsgRowStatus;
WriteMethod     write_cpuHealthMsgCpuId;
WriteMethod     write_cpuHealthMsgTempThres;
WriteMethod     write_cpuHealthMsgTemp;
WriteMethod     write_cpuHealthMsgVolThres;
WriteMethod     write_cpuHealthMsgVol;
WriteMethod     write_cpuHealthMsgRowStatus;



#endif                          /* CPUMANAGEMSG_H */
