/* Copyright (C) Rong Tao @Sylincom Beijing, 2019年 06月 14日 星期五 09:06:32 CST. */
/* 
 Copyright (C) Rong Tao @Beijing

 Permission is granted to copy, distribute and/or modify this document
 under the terms of the GNU Free Documentation License, Version 1.3
 or any later version published by the Free Software Foundation;
 with no Invariant Sections, no Front-Cover Texts, and no Back-Cover
 Texts. A copy of the license is included in the section entitled ‘‘GNU
 Free Documentation License’’.
   2019年 03月 14日 星期四 19:24:45 CST. 
*/
/* Copyright (C) Rong Tao @Sylincom Beijing, 2019年 03月 08日 星期五 08:10:29 CST. */
/* Copyright (C) Rong Tao @Sylincom Beijing, 2019年 03月 07日 星期四 20:28:03 CST. */
/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef FPGAASSETMSG_H
#define FPGAASSETMSG_H
#include <sbsconfig_common.h>
/*
 * function declarations 
 */
void            init_fpgaAssetMsg(void);
FindVarMethod   var_fpgaAssetMsg;
FindVarMethod   var_fpgaAssetMsgTable;
WriteMethod     write_fpgaAssetMsgpProductType;
WriteMethod     write_fpgaAssetMsgBoardType;
WriteMethod     write_fpgaAssetMsgFpgaServerName;
WriteMethod     write_fpgaAssetMsgFpgaServerSn;
WriteMethod     write_fpgaAssetMsgFpgaServerVersion;
WriteMethod     write_fpgaAssetMsgFpgaServerManufData;
WriteMethod     write_fpgaAssetMsgFpgaId;
WriteMethod     write_fpgaAssetMsgFpgaSlot;
WriteMethod     write_fpgaAssetMsgFpgaName;
WriteMethod     write_fpgaAssetMsgFpgaVersion;
WriteMethod     write_fpgaAssetMsgFpgaSn;
WriteMethod     write_fpgaAssetMsgFpgaFwVersion;
WriteMethod     write_fpgaAssetMsgRowStatus;

#endif                          /* FPGAASSETMSG_H */
