/* Copyright (C) Rong Tao @Sylincom Beijing, 2019年 06月 14日 星期五 09:06:32 CST. */
/* 
 Copyright (C) Rong Tao @Beijing

 Permission is granted to copy, distribute and/or modify this document
 under the terms of the GNU Free Documentation License, Version 1.3
 or any later version published by the Free Software Foundation;
 with no Invariant Sections, no Front-Cover Texts, and no Back-Cover
 Texts. A copy of the license is included in the section entitled ‘‘GNU
 Free Documentation License’’.
   2019年 03月 14日 星期四 19:24:45 CST. 
*/
/* Copyright (C) Rong Tao @Sylincom Beijing, 2019年 03月 08日 星期五 08:10:29 CST. */
/* Copyright (C) Rong Tao @Sylincom Beijing, 2019年 03月 07日 星期四 20:28:03 CST. */
/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef FPGAHEALTHMSG_H
#define FPGAHEALTHMSG_H
#include <sbsconfig_common.h>
/*
 * function declarations 
 */
void            init_fpgaHealthMsg(void);
FindVarMethod   var_fpgaHealthMsg;
FindVarMethod   var_fpgaHealthMsgTable;
WriteMethod     write_fpgaHealthMsgFpgaServerId;
WriteMethod     write_fpgaHealthMsgFpgaServerFanThres;
WriteMethod     write_fpgaHealthMsgFpgaServerFan;
WriteMethod     write_fpgaHealthMsgFpgaId;
WriteMethod     write_fpgaHealthMsgFpgaTempThres;
WriteMethod     write_fpgaHealthMsgFpgaTemp;
WriteMethod     write_fpgaHealthMsgFpgaVolThres;
WriteMethod     write_fpgaHealthMsgFpgaVol;
WriteMethod     write_fpgaHealthMsgRowStatus;

#endif                          /* FPGAHEALTHMSG_H */
