/* Copyright (C) Rong Tao @Sylincom Beijing, 2019年 06月 14日 星期五 09:06:32 CST. */
/* 
 Copyright (C) Rong Tao @Beijing

 Permission is granted to copy, distribute and/or modify this document
 under the terms of the GNU Free Documentation License, Version 1.3
 or any later version published by the Free Software Foundation;
 with no Invariant Sections, no Front-Cover Texts, and no Back-Cover
 Texts. A copy of the license is included in the section entitled ‘‘GNU
 Free Documentation License’’.
   2019年 03月 14日 星期四 19:24:45 CST. 
*/
/* Copyright (C) Rong Tao @Sylincom Beijing, 2019年 03月 08日 星期五 08:10:29 CST. */
/* Copyright (C) Rong Tao @Sylincom Beijing, 2019年 03月 07日 星期四 20:28:03 CST. */
/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef OMRRUNOTIFICATION_H
#define OMRRUNOTIFICATION_H
#include "sbs_type.h"
#include "rrus_mgmt_api_cfig_mgmt.h"
#include "sbs_log.h"
#include "om_common_h.h"

/*
 * function declarations 
 */
int             send_rruInitResp_trap(ICR_RRU_INIT_RESULT_TRAP *msg);
int             send_rruRingTestResp_trap(ICR_RRU_RING_TEST_RESULT *msg);
//int             send_rruResetResp_trap(ICR_RRU_SW_UPDATE_RESULT *msg);
int             send_rruSwUpdateResp_trap(ICR_RRU_SW_UPDATE_RESULT *msg);
int             send_cpriRingTestResp_trap(ICR_CPRI_RING_TEST_RESULT *msg);
int             send_cpriErrTestResp_trap(ICR_CPRI_SER_TEST_RESULT *msg);
int             send_cpriDelayCfgResp_trap(ICR_CPRI_TIME_DELAY_CFG_RESULT *msg);
int             send_cpriSingleCfgResp_trap(ICR_SINGLE_SEND_RESULT *msg);
INT32           handle_fn_rru_trap_msg(void* buf, UINT32 msg_len);

#endif                          /* OMRRUNOTIFICATION_H */
