/* Copyright (C) Rong Tao @Sylincom Beijing, 2019年 06月 14日 星期五 09:06:32 CST. */
/* 
 Copyright (C) Rong Tao @Beijing

 Permission is granted to copy, distribute and/or modify this document
 under the terms of the GNU Free Documentation License, Version 1.3
 or any later version published by the Free Software Foundation;
 with no Invariant Sections, no Front-Cover Texts, and no Back-Cover
 Texts. A copy of the license is included in the section entitled ‘‘GNU
 Free Documentation License’’.
   2019年 03月 14日 星期四 19:24:45 CST. 
*/
/* Copyright (C) Rong Tao @Sylincom Beijing, 2019年 03月 08日 星期五 08:10:29 CST. */
/* Copyright (C) Rong Tao @Sylincom Beijing, 2019年 03月 07日 星期四 20:28:03 CST. */
/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef PROTOCOLTOPHYCONFIGINFO_H
#define PROTOCOLTOPHYCONFIGINFO_H
#include "sbsconfig_common.h"

typedef struct{
	int protocolToPhyConfigInfophyCfg;
	int protocolToPhyConfigInfopuschDtxThresh;
	int protocolToPhyConfigInfomuxPuschANDT;
	int protocolToPhyConfigInfomuxPuschCDT;
	int protocolToPhyConfigInfomuxPuschRDT;
	int protocolToPhyConfigInfopucchRbStart;
	int protocolToPhyConfigInfopucchF1DT;
	int protocolToPhyConfigInfopucchF2DT;
	int protocolToPhyConfigInfoprachThresh;
	char protocolToPhyConfigInforadioAccessMode[STR_LEN_PROTOCOL];
	int protocolToPhyConfigInfopsyncPower;
	int protocolToPhyConfigInfossyncPower;
	int protocolToPhyConfigInfoimcs;
	char protocolToPhyConfigInfomumimo[STR_LEN_PROTOCOL];
	char protocolToPhyConfigInfosyncantselection[STR_LEN_PROTOCOL];
	int protocolToPhyConfigInfocarrierAggrLev;
	char protocolToPhyConfigInfooperationalMode[STR_LEN_PROTOCOL];

	int old_protocolToPhyConfigInfophyCfg;
	int old_protocolToPhyConfigInfopuschDtxThresh;
	int old_protocolToPhyConfigInfomuxPuschANDT;
	int old_protocolToPhyConfigInfomuxPuschCDT;
	int old_protocolToPhyConfigInfomuxPuschRDT;
	int old_protocolToPhyConfigInfopucchRbStart;
	int old_protocolToPhyConfigInfopucchF1DT;
	int old_protocolToPhyConfigInfopucchF2DT;
	int old_protocolToPhyConfigInfoprachThresh;
	char old_protocolToPhyConfigInforadioAccessMode[STR_LEN_PROTOCOL];
	int old_protocolToPhyConfigInfopsyncPower;
	int old_protocolToPhyConfigInfossyncPower;
	int old_protocolToPhyConfigInfoimcs;
	char old_protocolToPhyConfigInfomumimo[STR_LEN_PROTOCOL];
	char old_protocolToPhyConfigInfosyncantselection[STR_LEN_PROTOCOL];
	int old_protocolToPhyConfigInfocarrierAggrLev;
	char old_protocolToPhyConfigInfooperationalMode[STR_LEN_PROTOCOL];

}sbs_protocolToPhyConfigInfo_Scalar_t;
/*
 * function declarations 
 */
void            init_protocolToPhyConfigInfo(void);
Netsnmp_Node_Handler handle_protocolToPhyConfigInfophyCfg;
Netsnmp_Node_Handler handle_protocolToPhyConfigInfopuschDtxThresh;
Netsnmp_Node_Handler handle_protocolToPhyConfigInfomuxPuschANDT;
Netsnmp_Node_Handler handle_protocolToPhyConfigInfomuxPuschCDT;
Netsnmp_Node_Handler handle_protocolToPhyConfigInfomuxPuschRDT;
Netsnmp_Node_Handler handle_protocolToPhyConfigInfopucchRbStart;
Netsnmp_Node_Handler handle_protocolToPhyConfigInfopucchF1DT;
Netsnmp_Node_Handler handle_protocolToPhyConfigInfopucchF2DT;
Netsnmp_Node_Handler handle_protocolToPhyConfigInfoprachThresh;
Netsnmp_Node_Handler handle_protocolToPhyConfigInforadioAccessMode;
Netsnmp_Node_Handler handle_protocolToPhyConfigInfopsyncPower;
Netsnmp_Node_Handler handle_protocolToPhyConfigInfossyncPower;
Netsnmp_Node_Handler handle_protocolToPhyConfigInfoimcs;
Netsnmp_Node_Handler handle_protocolToPhyConfigInfomumimo;
Netsnmp_Node_Handler handle_protocolToPhyConfigInfosyncantselection;
Netsnmp_Node_Handler handle_protocolToPhyConfigInfocarrierAggrLev;
Netsnmp_Node_Handler handle_protocolToPhyConfigInfooperationalMode;

#endif                          /* PROTOCOLTOPHYCONFIGINFO_H */
