/* Copyright (C) Rong Tao @Sylincom Beijing, 2019年 06月 14日 星期五 09:06:32 CST. */
/* 
 Copyright (C) Rong Tao @Beijing

 Permission is granted to copy, distribute and/or modify this document
 under the terms of the GNU Free Documentation License, Version 1.3
 or any later version published by the Free Software Foundation;
 with no Invariant Sections, no Front-Cover Texts, and no Back-Cover
 Texts. A copy of the license is included in the section entitled ‘‘GNU
 Free Documentation License’’.
   2019年 03月 14日 星期四 19:24:45 CST. 
*/
/* Copyright (C) Rong Tao @Sylincom Beijing, 2019年 03月 08日 星期五 08:10:29 CST. */
/* Copyright (C) Rong Tao @Sylincom Beijing, 2019年 03月 07日 星期四 20:28:03 CST. */
/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef RRUINITINFO_H
#define RRUINITINFO_H

#include "sbs_type.h"
#include "sbs_log.h"
#include "rrus_mgmt_api_cfig_mgmt.h"
#include "om_common_h.h"
#include "cfig_common.h"

#define RRUINITINFOTABLE_INDEX_POS 14
#define RRU_SN_LEN 16
#define RRU_PATH_STATE_LEN 8
//#define MAX_RRU_ID 0XFFFFFFFF

	
typedef struct
{
	u_long			rruInitMsgIndex;
	u_long			rruInitMsgRruId;
	char			rruInitMsgSerialNo[16];
	size_t			rruInitMsgSerialNo_len;
	u_long			rruInitMsgPeriod;
	u_long			rruInitMsgVswrThres1;
	u_long			rruInitMsgVswrThres2;
	long			rruInitMsgUpThres;
	long			rruInitMsgLowThres;
	u_long			rruInitMsgAntMode;
	u_long			rruInitMsgAntSetNo;
	u_long			rruInitMsgAntState;
	char			rruInitMsgUpPathState[8];
	size_t			rruInitMsgUpPathState_len;
	char			rruInitMsgDwPathState[8];
	size_t			rruInitMsgDwPathState_len;
	long			rruInitMsgRowStatus;
	UINT16			fin_flag;
}rruInitMsgTable;

void            init_rruInitInfo(void);
void            charVec2intVec(int * int_vec, char *char_vec, int len);
FindVarMethod   var_rruInitInfo;
FindVarMethod   var_rruInitMsgTable;
WriteMethod     write_rruInitMsgRruId;
WriteMethod     write_rruInitMsgSerialNo;
WriteMethod     write_rruInitMsgPeriod;
WriteMethod     write_rruInitMsgVswrThres1;
WriteMethod     write_rruInitMsgVswrThres2;
WriteMethod     write_rruInitMsgUpThres;
WriteMethod     write_rruInitMsgLowThres;
WriteMethod     write_rruInitMsgAntMode;
WriteMethod     write_rruInitMsgAntSetNo;
WriteMethod     write_rruInitMsgAntState;
WriteMethod     write_rruInitMsgUpPathState;
WriteMethod     write_rruInitMsgDwPathState;
WriteMethod     write_rruInitMsgRowStatus;

#endif                          /* RRUINITINFO_H */
