/* Copyright (C) Rong Tao @Sylincom Beijing, 2019年 06月 14日 星期五 09:06:45 CST. */
/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef CELLMGMTGROUP_H
#define CELLMGMTGROUP_H

#define log_mibs_debug() printf("%s:%d\n", __func__, __LINE__)

/*
 * function declarations 
 */
void            init_cellMgmtGroup(void);
FindVarMethod   var_cellMgmtGroup;
FindVarMethod   var_cellMgmtConfigInfoTable;
WriteMethod     write_cellMgmtConfigInfoCellDescribe;
WriteMethod     write_cellMgmtConfigInfoCellMode;
WriteMethod     write_cellMgmtConfigInfoCellType;
WriteMethod     write_cellMgmtConfigInfoCellRole;
WriteMethod     write_cellMgmtConfigInfoRRUSN;
WriteMethod     write_cellMgmtConfigInfoRRUID;
WriteMethod     write_cellMgmtConfigInfoRRUIP;
WriteMethod     write_cellMgmtConfigInfoRRUPort;
WriteMethod     write_cellMgmtConfigInfoPowerFactor;
WriteMethod     write_cellMgmtConfigInfoBBUIP;
WriteMethod     write_cellMgmtConfigInfoBBUPort;
WriteMethod     write_cellMgmtConfigInfoCellPerfOnOff;
WriteMethod     write_cellMgmtConfigInfoRowStatus;

#endif                          /* CELLMGMTGROUP_H */
