/* Copyright (C) Rong Tao @Sylincom Beijing, 2019年 06月 14日 星期五 09:06:45 CST. */
/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "cellMgmtGroup.h"

#include<signal.h>

/*
 * cellMgmtGroup_variables_oid:
 *   this is the top level oid that we want to register under.  This
 *   is essentially a prefix, with the suffix appearing in the
 *   variable below.
 */

oid             cellMgmtGroup_variables_oid[] =
    { 1, 3, 6, 1, 4, 1, 1, 2, 2 };

/*
 * variable4 cellMgmtGroup_variables:
 *   this variable defines function callbacks and type return information 
 *   for the cellMgmtGroup mib section 
 */

struct variable4 cellMgmtGroup_variables[] = {
    /*
     * magic number        , variable type , ro/rw , callback fn  , L, oidsuffix 
     */

#define CELLMGMTCONFIGINFOINDEX		1
    {CELLMGMTCONFIGINFOINDEX, ASN_INTEGER, NETSNMP_OLDAPI_RONLY,
     var_cellMgmtConfigInfoTable, 3, {1, 1, 1}},
#define CELLMGMTCONFIGINFOCELLGLOBALID		2
    {CELLMGMTCONFIGINFOCELLGLOBALID, ASN_INTEGER, NETSNMP_OLDAPI_RWRITE,
     var_cellMgmtConfigInfoTable, 3, {1, 1, 2}},
#define CELLMGMTCONFIGINFOCELLID		3
    {CELLMGMTCONFIGINFOCELLID, ASN_INTEGER, NETSNMP_OLDAPI_RWRITE,
     var_cellMgmtConfigInfoTable, 3, {1, 1, 3}},
#define CELLMGMTCONFIGINFOCELLSNMPINDEX		4
    {CELLMGMTCONFIGINFOCELLSNMPINDEX, ASN_INTEGER, NETSNMP_OLDAPI_RWRITE,
     var_cellMgmtConfigInfoTable, 3, {1, 1, 4}},
#define CELLMGMTCONFIGINFOCELLMODE		5
    {CELLMGMTCONFIGINFOCELLMODE, ASN_INTEGER, NETSNMP_OLDAPI_RWRITE,
     var_cellMgmtConfigInfoTable, 3, {1, 1, 5}},
#define CELLMGMTCONFIGINFOCELLTYPE		6
    {CELLMGMTCONFIGINFOCELLTYPE, ASN_INTEGER, NETSNMP_OLDAPI_RWRITE,
     var_cellMgmtConfigInfoTable, 3, {1, 1, 6}},
#define CELLMGMTCONFIGINFOCELLROLE		7
    {CELLMGMTCONFIGINFOCELLROLE, ASN_INTEGER, NETSNMP_OLDAPI_RWRITE,
     var_cellMgmtConfigInfoTable, 3, {1, 1, 7}},
#define CELLMGMTCONFIGINFORRUSN		8
    {CELLMGMTCONFIGINFORRUSN, ASN_OCTET_STR, NETSNMP_OLDAPI_RWRITE,
     var_cellMgmtConfigInfoTable, 3, {1, 1, 8}},
#define CELLMGMTCONFIGINFORRUID		9
    {CELLMGMTCONFIGINFORRUID, ASN_INTEGER, NETSNMP_OLDAPI_RWRITE,
     var_cellMgmtConfigInfoTable, 3, {1, 1, 9}},
#define CELLMGMTCONFIGINFORRUIP		10
    {CELLMGMTCONFIGINFORRUIP, ASN_OCTET_STR, NETSNMP_OLDAPI_RWRITE,
     var_cellMgmtConfigInfoTable, 3, {1, 1, 10}},
#define CELLMGMTCONFIGINFORRUPORT		11
    {CELLMGMTCONFIGINFORRUPORT, ASN_INTEGER, NETSNMP_OLDAPI_RWRITE,
     var_cellMgmtConfigInfoTable, 3, {1, 1, 11}},
#define CELLMGMTCONFIGINFOPOWERFACTOR		12
    {CELLMGMTCONFIGINFOPOWERFACTOR, ASN_INTEGER, NETSNMP_OLDAPI_RWRITE,
     var_cellMgmtConfigInfoTable, 3, {1, 1, 12}},
#define CELLMGMTCONFIGINFOBBUIP		13
    {CELLMGMTCONFIGINFOBBUIP, ASN_OCTET_STR, NETSNMP_OLDAPI_RWRITE,
     var_cellMgmtConfigInfoTable, 3, {1, 1, 13}},
#define CELLMGMTCONFIGINFOBBUPORT		14
    {CELLMGMTCONFIGINFOBBUPORT, ASN_INTEGER, NETSNMP_OLDAPI_RWRITE,
     var_cellMgmtConfigInfoTable, 3, {1, 1, 14}},
#define CELLMGMTCONFIGINFOROWSTATUS		15
    {CELLMGMTCONFIGINFOROWSTATUS, ASN_INTEGER, NETSNMP_OLDAPI_RWRITE,
     var_cellMgmtConfigInfoTable, 3, {1, 1, 15}},
};

/*
 * (L = length of the oidsuffix) 
 */


/** Initializes the cellMgmtGroup module */
void
init_cellMgmtGroup(void)
{
    debug();
    DEBUGMSGTL(("cellMgmtGroup", "Initializing\n"));
    debug();
    /*
     * register ourselves with the agent to handle our mib tree 
     */
    REGISTER_MIB("cellMgmtGroup", cellMgmtGroup_variables, variable4,
                 cellMgmtGroup_variables_oid);
    debug();
    /*
     * place any other initialization junk you need here 
     */
}

/*
 * var_cellMgmtGroup():
 *   This function is called every time the agent gets a request for
 *   a scalar variable that might be found within your mib section
 *   registered above.  It is up to you to do the right thing and
 *   return the correct value.
 *     You should also correct the value of "var_len" if necessary.
 *
 *   Please see the documentation for more information about writing
 *   module extensions, and check out the examples in the examples
 *   and mibII directories.
 */
unsigned char  *
var_cellMgmtGroup(struct variable *vp,
                  oid * name,
                  size_t *length,
                  int exact, size_t *var_len, WriteMethod ** write_method)
{
    /*
     * variables we may use later 
     */
    static long     long_ret;
    static u_long   ulong_ret;
    static unsigned char string[SPRINT_MAX_LEN];
    static oid      objid[MAX_OID_LEN];
    static struct counter64 c64;
    
    debug();
    
    if (header_generic(vp, name, length, exact, var_len, write_method)
        == MATCH_FAILED)
        return NULL;

    debug();
        
    /*
     * this is where we do the value assignments for the mib results.
     */
    switch (vp->magic) {
    default:
        ERROR_MSG("");
    }
    return NULL;
}


/*
 * var_cellMgmtConfigInfoTable():
 *   Handle this table separately from the scalar value case.
 *   The workings of this are basically the same as for var_cellMgmtGroup above.
 */
unsigned char  *
var_cellMgmtConfigInfoTable(struct variable *vp,
                            oid * name,
                            size_t *length,
                            int exact,
                            size_t *var_len, WriteMethod ** write_method)
{
    /*
     * variables we may use later 
     */
    static long     long_ret;
    static u_long   ulong_ret;
    static unsigned char string[SPRINT_MAX_LEN];
    static oid      objid[MAX_OID_LEN];
    static struct counter64 c64;

    debug();
    
	/**
	 *	Define
	 */
	static int TABLE_SIZE = 10;
	static int VAR = 1, VALUE = 2;


    /*
     * This assumes that the table is a 'simple' table.
     *  See the implementation documentation for the meaning of this.
     *  You will need to provide the correct value for the TABLE_SIZE parameter
     *
     * If this table does not meet the requirements for a simple table,
     *  you will need to provide the replacement code yourself.
     *  Mib2c is not smart enough to write this for you.
     *    Again, see the implementation documentation for what is required.
     */
    if (header_simple_table
        (vp, name, length, exact, var_len, write_method, TABLE_SIZE)
        == MATCH_FAILED)
        return NULL;

    debug();
        
    /*
     * this is where we do the value assignments for the mib results.
     */
    switch (vp->magic) {
    case CELLMGMTCONFIGINFOINDEX:
        debug();
        VAR = VALUE;            /* XXX */
        return (u_char *) & VAR;
    case CELLMGMTCONFIGINFOCELLGLOBALID:
        debug();
        *write_method = write_cellMgmtConfigInfoCellGlobalID;
        VAR = VALUE;            /* XXX */
        return (u_char *) & VAR;
    case CELLMGMTCONFIGINFOCELLID:
        debug();
        *write_method = write_cellMgmtConfigInfoCellID;
        VAR = VALUE;            /* XXX */
        return (u_char *) & VAR;
    case CELLMGMTCONFIGINFOCELLSNMPINDEX:
        debug();
        *write_method = write_cellMgmtConfigInfoCellSNMPIndex;
        VAR = VALUE;            /* XXX */
        return (u_char *) & VAR;
    case CELLMGMTCONFIGINFOCELLMODE:
        debug();
        *write_method = write_cellMgmtConfigInfoCellMode;
        VAR = VALUE;            /* XXX */
        return (u_char *) & VAR;
    case CELLMGMTCONFIGINFOCELLTYPE:
        debug();
        *write_method = write_cellMgmtConfigInfoCellType;
        VAR = VALUE;            /* XXX */
        return (u_char *) & VAR;
    case CELLMGMTCONFIGINFOCELLROLE:
        debug();
        *write_method = write_cellMgmtConfigInfoCellRole;
        VAR = VALUE;            /* XXX */
        return (u_char *) & VAR;
    case CELLMGMTCONFIGINFORRUSN:
        debug();
        *write_method = write_cellMgmtConfigInfoRRUSN;
        VAR = VALUE;            /* XXX */
        return (u_char *) & VAR;
    case CELLMGMTCONFIGINFORRUID:
        *write_method = write_cellMgmtConfigInfoRRUID;
        VAR = VALUE;            /* XXX */
        return (u_char *) & VAR;
    case CELLMGMTCONFIGINFORRUIP:
        debug();
        *write_method = write_cellMgmtConfigInfoRRUIP;
        VAR = VALUE;            /* XXX */
        return (u_char *) & VAR;
    case CELLMGMTCONFIGINFORRUPORT:
        debug();
        *write_method = write_cellMgmtConfigInfoRRUPort;
        VAR = VALUE;            /* XXX */
        return (u_char *) & VAR;
    case CELLMGMTCONFIGINFOPOWERFACTOR:
        debug();
        *write_method = write_cellMgmtConfigInfoPowerFactor;
        VAR = VALUE;            /* XXX */
        return (u_char *) & VAR;
    case CELLMGMTCONFIGINFOBBUIP:
        debug();
        *write_method = write_cellMgmtConfigInfoBBUIP;
        VAR = VALUE;            /* XXX */
        return (u_char *) & VAR;
    case CELLMGMTCONFIGINFOBBUPORT:
        *write_method = write_cellMgmtConfigInfoBBUPort;
        VAR = VALUE;            /* XXX */
        return (u_char *) & VAR;
    case CELLMGMTCONFIGINFOROWSTATUS:
        *write_method = write_cellMgmtConfigInfoRowStatus;
        VAR = VALUE;            /* XXX */
        return (u_char *) & VAR;
    default:
        ERROR_MSG("");
    }
    return NULL;
}


int
write_cellMgmtConfigInfoCellGlobalID(int action,
                                     u_char * var_val,
                                     u_char var_val_type,
                                     size_t var_val_len,
                                     u_char * statP,
                                     oid * name, size_t name_len)
{
    long            value;
    int             size;
    debug();
    switch (action) {
    case RESERVE1:
        if (var_val_type != ASN_INTEGER) {
            fprintf(stderr, "write to cellMgmtGroup not ASN_INTEGER\n");
            return SNMP_ERR_WRONGTYPE;
        }
        if (var_val_len > sizeof(long)) {
            fprintf(stderr, "write to cellMgmtGroup: bad length\n");
            return SNMP_ERR_WRONGLENGTH;
        }
        break;

    case RESERVE2:
        size = var_val_len;
        value = *(long *) var_val;
        debug();
        break;

    case FREE:
        /*
         * Release any resources that have been allocated 
         */
        debug();
        break;

    case ACTION:
        /*
         * The variable has been stored in 'value' for you to use,
         * and you have just been asked to do something with it.
         * Note that anything done here must be reversable in the UNDO case
         */
        debug();
        break;

    case UNDO:
        /*
         * Back out any changes made in the ACTION case 
         */
        debug();
        break;

    case COMMIT:
        /*
         * Things are working well, so it's now safe to make the change
         * permanently.  Make sure that anything done here can't fail!
         */
        debug();
        break;
    }
    return SNMP_ERR_NOERROR;
}

int
write_cellMgmtConfigInfoCellID(int action,
                               u_char * var_val,
                               u_char var_val_type,
                               size_t var_val_len,
                               u_char * statP, oid * name, size_t name_len)
{
    long            value;
    int             size;

    switch (action) {
    case RESERVE1:
        if (var_val_type != ASN_INTEGER) {
            fprintf(stderr, "write to cellMgmtGroup not ASN_INTEGER\n");
            return SNMP_ERR_WRONGTYPE;
        }
        if (var_val_len > sizeof(long)) {
            fprintf(stderr, "write to cellMgmtGroup: bad length\n");
            return SNMP_ERR_WRONGLENGTH;
        }
        break;

    case RESERVE2:
        size = var_val_len;
        value = *(long *) var_val;

        break;

    case FREE:
        /*
         * Release any resources that have been allocated 
         */
        break;

    case ACTION:
        /*
         * The variable has been stored in 'value' for you to use,
         * and you have just been asked to do something with it.
         * Note that anything done here must be reversable in the UNDO case
         */
        break;

    case UNDO:
        /*
         * Back out any changes made in the ACTION case 
         */
        break;

    case COMMIT:
        /*
         * Things are working well, so it's now safe to make the change
         * permanently.  Make sure that anything done here can't fail!
         */
        break;
    }
    return SNMP_ERR_NOERROR;
}

int
write_cellMgmtConfigInfoCellSNMPIndex(int action,
                                      u_char * var_val,
                                      u_char var_val_type,
                                      size_t var_val_len,
                                      u_char * statP,
                                      oid * name, size_t name_len)
{
    long            value;
    int             size;
    debug();
    switch (action) {
    case RESERVE1:debug();
        if (var_val_type != ASN_INTEGER) {
            fprintf(stderr, "write to cellMgmtGroup not ASN_INTEGER\n");
            return SNMP_ERR_WRONGTYPE;
        }
        if (var_val_len > sizeof(long)) {
            fprintf(stderr, "write to cellMgmtGroup: bad length\n");
            return SNMP_ERR_WRONGLENGTH;
        }
        break;

    case RESERVE2:debug();
        size = var_val_len;
        value = *(long *) var_val;

        break;

    case FREE:debug();
        /*
         * Release any resources that have been allocated 
         */
        break;

    case ACTION:debug();
        /*
         * The variable has been stored in 'value' for you to use,
         * and you have just been asked to do something with it.
         * Note that anything done here must be reversable in the UNDO case
         */
        break;

    case UNDO:debug();
        /*
         * Back out any changes made in the ACTION case 
         */
        break;

    case COMMIT:debug();
        /*
         * Things are working well, so it's now safe to make the change
         * permanently.  Make sure that anything done here can't fail!
         */
        break;
    }
    debug();
    return SNMP_ERR_NOERROR;
}

int
write_cellMgmtConfigInfoCellMode(int action,
                                 u_char * var_val,
                                 u_char var_val_type,
                                 size_t var_val_len,
                                 u_char * statP,
                                 oid * name, size_t name_len)
{
    long            value;
    int             size;

    switch (action) {
    case RESERVE1:
        if (var_val_type != ASN_INTEGER) {
            fprintf(stderr, "write to cellMgmtGroup not ASN_INTEGER\n");
            return SNMP_ERR_WRONGTYPE;
        }
        if (var_val_len > sizeof(long)) {
            fprintf(stderr, "write to cellMgmtGroup: bad length\n");
            return SNMP_ERR_WRONGLENGTH;
        }
        break;

    case RESERVE2:
        size = var_val_len;
        value = *(long *) var_val;

        break;

    case FREE:
        /*
         * Release any resources that have been allocated 
         */
        break;

    case ACTION:
        /*
         * The variable has been stored in 'value' for you to use,
         * and you have just been asked to do something with it.
         * Note that anything done here must be reversable in the UNDO case
         */
        break;

    case UNDO:
        /*
         * Back out any changes made in the ACTION case 
         */
        break;

    case COMMIT:
        /*
         * Things are working well, so it's now safe to make the change
         * permanently.  Make sure that anything done here can't fail!
         */
        break;
    }
    return SNMP_ERR_NOERROR;
}

int
write_cellMgmtConfigInfoCellType(int action,
                                 u_char * var_val,
                                 u_char var_val_type,
                                 size_t var_val_len,
                                 u_char * statP,
                                 oid * name, size_t name_len)
{
    long            value;
    int             size;

    switch (action) {
    case RESERVE1:
        if (var_val_type != ASN_INTEGER) {
            fprintf(stderr, "write to cellMgmtGroup not ASN_INTEGER\n");
            return SNMP_ERR_WRONGTYPE;
        }
        if (var_val_len > sizeof(long)) {
            fprintf(stderr, "write to cellMgmtGroup: bad length\n");
            return SNMP_ERR_WRONGLENGTH;
        }
        break;

    case RESERVE2:
        size = var_val_len;
        value = *(long *) var_val;

        break;

    case FREE:
        /*
         * Release any resources that have been allocated 
         */
        break;

    case ACTION:
        /*
         * The variable has been stored in 'value' for you to use,
         * and you have just been asked to do something with it.
         * Note that anything done here must be reversable in the UNDO case
         */
        break;

    case UNDO:
        /*
         * Back out any changes made in the ACTION case 
         */
        break;

    case COMMIT:
        /*
         * Things are working well, so it's now safe to make the change
         * permanently.  Make sure that anything done here can't fail!
         */
        break;
    }
    return SNMP_ERR_NOERROR;
}

int
write_cellMgmtConfigInfoCellRole(int action,
                                 u_char * var_val,
                                 u_char var_val_type,
                                 size_t var_val_len,
                                 u_char * statP,
                                 oid * name, size_t name_len)
{
    long            value;
    int             size;

    switch (action) {
    case RESERVE1:
        if (var_val_type != ASN_INTEGER) {
            fprintf(stderr, "write to cellMgmtGroup not ASN_INTEGER\n");
            return SNMP_ERR_WRONGTYPE;
        }
        if (var_val_len > sizeof(long)) {
            fprintf(stderr, "write to cellMgmtGroup: bad length\n");
            return SNMP_ERR_WRONGLENGTH;
        }
        break;

    case RESERVE2:
        size = var_val_len;
        value = *(long *) var_val;

        break;

    case FREE:
        /*
         * Release any resources that have been allocated 
         */
        break;

    case ACTION:
        /*
         * The variable has been stored in 'value' for you to use,
         * and you have just been asked to do something with it.
         * Note that anything done here must be reversable in the UNDO case
         */
        break;

    case UNDO:
        /*
         * Back out any changes made in the ACTION case 
         */
        break;

    case COMMIT:
        /*
         * Things are working well, so it's now safe to make the change
         * permanently.  Make sure that anything done here can't fail!
         */
        break;
    }
    return SNMP_ERR_NOERROR;
}

int
write_cellMgmtConfigInfoRRUSN(int action,
                              u_char * var_val,
                              u_char var_val_type,
                              size_t var_val_len,
                              u_char * statP, oid * name, size_t name_len)
{
    char            value;
    int             size;

    switch (action) {
    case RESERVE1:
        if (var_val_type != ASN_OCTET_STR) {
            fprintf(stderr, "write to cellMgmtGroup not ASN_OCTET_STR\n");
            return SNMP_ERR_WRONGTYPE;
        }
        if (var_val_len > sizeof(char)) {
            fprintf(stderr, "write to cellMgmtGroup: bad length\n");
            return SNMP_ERR_WRONGLENGTH;
        }
        break;

    case RESERVE2:
        size = var_val_len;
        value = *(char *) var_val;

        break;

    case FREE:
        /*
         * Release any resources that have been allocated 
         */
        break;

    case ACTION:
        /*
         * The variable has been stored in 'value' for you to use,
         * and you have just been asked to do something with it.
         * Note that anything done here must be reversable in the UNDO case
         */
        break;

    case UNDO:
        /*
         * Back out any changes made in the ACTION case 
         */
        break;

    case COMMIT:
        /*
         * Things are working well, so it's now safe to make the change
         * permanently.  Make sure that anything done here can't fail!
         */
        break;
    }
    return SNMP_ERR_NOERROR;
}

int
write_cellMgmtConfigInfoRRUID(int action,
                              u_char * var_val,
                              u_char var_val_type,
                              size_t var_val_len,
                              u_char * statP, oid * name, size_t name_len)
{
    long            value;
    int             size;

    switch (action) {
    case RESERVE1:
        if (var_val_type != ASN_INTEGER) {
            fprintf(stderr, "write to cellMgmtGroup not ASN_INTEGER\n");
            return SNMP_ERR_WRONGTYPE;
        }
        if (var_val_len > sizeof(long)) {
            fprintf(stderr, "write to cellMgmtGroup: bad length\n");
            return SNMP_ERR_WRONGLENGTH;
        }
        break;

    case RESERVE2:
        size = var_val_len;
        value = *(long *) var_val;

        break;

    case FREE:
        /*
         * Release any resources that have been allocated 
         */
        break;

    case ACTION:
        /*
         * The variable has been stored in 'value' for you to use,
         * and you have just been asked to do something with it.
         * Note that anything done here must be reversable in the UNDO case
         */
        break;

    case UNDO:
        /*
         * Back out any changes made in the ACTION case 
         */
        break;

    case COMMIT:
        /*
         * Things are working well, so it's now safe to make the change
         * permanently.  Make sure that anything done here can't fail!
         */
        break;
    }
    return SNMP_ERR_NOERROR;
}

int
write_cellMgmtConfigInfoRRUIP(int action,
                              u_char * var_val,
                              u_char var_val_type,
                              size_t var_val_len,
                              u_char * statP, oid * name, size_t name_len)
{
    char            value;
    int             size;

    switch (action) {
    case RESERVE1:
        if (var_val_type != ASN_OCTET_STR) {
            fprintf(stderr, "write to cellMgmtGroup not ASN_OCTET_STR\n");
            return SNMP_ERR_WRONGTYPE;
        }
        if (var_val_len > sizeof(char)) {
            fprintf(stderr, "write to cellMgmtGroup: bad length\n");
            return SNMP_ERR_WRONGLENGTH;
        }
        break;

    case RESERVE2:
        size = var_val_len;
        value = *(char *) var_val;

        break;

    case FREE:
        /*
         * Release any resources that have been allocated 
         */
        break;

    case ACTION:
        /*
         * The variable has been stored in 'value' for you to use,
         * and you have just been asked to do something with it.
         * Note that anything done here must be reversable in the UNDO case
         */
        break;

    case UNDO:
        /*
         * Back out any changes made in the ACTION case 
         */
        break;

    case COMMIT:
        /*
         * Things are working well, so it's now safe to make the change
         * permanently.  Make sure that anything done here can't fail!
         */
        break;
    }
    return SNMP_ERR_NOERROR;
}

int
write_cellMgmtConfigInfoRRUPort(int action,
                                u_char * var_val,
                                u_char var_val_type,
                                size_t var_val_len,
                                u_char * statP,
                                oid * name, size_t name_len)
{
    long            value;
    int             size;

    switch (action) {
    case RESERVE1:
        if (var_val_type != ASN_INTEGER) {
            fprintf(stderr, "write to cellMgmtGroup not ASN_INTEGER\n");
            return SNMP_ERR_WRONGTYPE;
        }
        if (var_val_len > sizeof(long)) {
            fprintf(stderr, "write to cellMgmtGroup: bad length\n");
            return SNMP_ERR_WRONGLENGTH;
        }
        break;

    case RESERVE2:
        size = var_val_len;
        value = *(long *) var_val;

        break;

    case FREE:
        /*
         * Release any resources that have been allocated 
         */
        break;

    case ACTION:
        /*
         * The variable has been stored in 'value' for you to use,
         * and you have just been asked to do something with it.
         * Note that anything done here must be reversable in the UNDO case
         */
        break;

    case UNDO:
        /*
         * Back out any changes made in the ACTION case 
         */
        break;

    case COMMIT:
        /*
         * Things are working well, so it's now safe to make the change
         * permanently.  Make sure that anything done here can't fail!
         */
        break;
    }
    return SNMP_ERR_NOERROR;
}

int
write_cellMgmtConfigInfoPowerFactor(int action,
                                    u_char * var_val,
                                    u_char var_val_type,
                                    size_t var_val_len,
                                    u_char * statP,
                                    oid * name, size_t name_len)
{
    long            value;
    int             size;

    switch (action) {
    case RESERVE1:
        if (var_val_type != ASN_INTEGER) {
            fprintf(stderr, "write to cellMgmtGroup not ASN_INTEGER\n");
            return SNMP_ERR_WRONGTYPE;
        }
        if (var_val_len > sizeof(long)) {
            fprintf(stderr, "write to cellMgmtGroup: bad length\n");
            return SNMP_ERR_WRONGLENGTH;
        }
        break;

    case RESERVE2:
        size = var_val_len;
        value = *(long *) var_val;

        break;

    case FREE:
        /*
         * Release any resources that have been allocated 
         */
        break;

    case ACTION:
        /*
         * The variable has been stored in 'value' for you to use,
         * and you have just been asked to do something with it.
         * Note that anything done here must be reversable in the UNDO case
         */
        break;

    case UNDO:
        /*
         * Back out any changes made in the ACTION case 
         */
        break;

    case COMMIT:
        /*
         * Things are working well, so it's now safe to make the change
         * permanently.  Make sure that anything done here can't fail!
         */
        break;
    }
    return SNMP_ERR_NOERROR;
}

int
write_cellMgmtConfigInfoBBUIP(int action,
                              u_char * var_val,
                              u_char var_val_type,
                              size_t var_val_len,
                              u_char * statP, oid * name, size_t name_len)
{
    char            value;
    int             size;

    switch (action) {
    case RESERVE1:
        if (var_val_type != ASN_OCTET_STR) {
            fprintf(stderr, "write to cellMgmtGroup not ASN_OCTET_STR\n");
            return SNMP_ERR_WRONGTYPE;
        }
        if (var_val_len > sizeof(char)) {
            fprintf(stderr, "write to cellMgmtGroup: bad length\n");
            return SNMP_ERR_WRONGLENGTH;
        }
        break;

    case RESERVE2:
        size = var_val_len;
        value = *(char *) var_val;

        break;

    case FREE:
        /*
         * Release any resources that have been allocated 
         */
        break;

    case ACTION:
        /*
         * The variable has been stored in 'value' for you to use,
         * and you have just been asked to do something with it.
         * Note that anything done here must be reversable in the UNDO case
         */
        break;

    case UNDO:
        /*
         * Back out any changes made in the ACTION case 
         */
        break;

    case COMMIT:
        /*
         * Things are working well, so it's now safe to make the change
         * permanently.  Make sure that anything done here can't fail!
         */
        break;
    }
    return SNMP_ERR_NOERROR;
}

int
write_cellMgmtConfigInfoBBUPort(int action,
                                u_char * var_val,
                                u_char var_val_type,
                                size_t var_val_len,
                                u_char * statP,
                                oid * name, size_t name_len)
{
    long            value;
    int             size;

    switch (action) {
    case RESERVE1:
        if (var_val_type != ASN_INTEGER) {
            fprintf(stderr, "write to cellMgmtGroup not ASN_INTEGER\n");
            return SNMP_ERR_WRONGTYPE;
        }
        if (var_val_len > sizeof(long)) {
            fprintf(stderr, "write to cellMgmtGroup: bad length\n");
            return SNMP_ERR_WRONGLENGTH;
        }
        break;

    case RESERVE2:
        size = var_val_len;
        value = *(long *) var_val;

        break;

    case FREE:
        /*
         * Release any resources that have been allocated 
         */
        break;

    case ACTION:
        /*
         * The variable has been stored in 'value' for you to use,
         * and you have just been asked to do something with it.
         * Note that anything done here must be reversable in the UNDO case
         */
        break;

    case UNDO:
        /*
         * Back out any changes made in the ACTION case 
         */
        break;

    case COMMIT:
        /*
         * Things are working well, so it's now safe to make the change
         * permanently.  Make sure that anything done here can't fail!
         */
        break;
    }
    return SNMP_ERR_NOERROR;
}

int
write_cellMgmtConfigInfoRowStatus(int action,
                                  u_char * var_val,
                                  u_char var_val_type,
                                  size_t var_val_len,
                                  u_char * statP,
                                  oid * name, size_t name_len)
{
    long            value;
    int             size;

    switch (action) {
    case RESERVE1:
        if (var_val_type != ASN_INTEGER) {
            fprintf(stderr, "write to cellMgmtGroup not ASN_INTEGER\n");
            return SNMP_ERR_WRONGTYPE;
        }
        if (var_val_len > sizeof(long)) {
            fprintf(stderr, "write to cellMgmtGroup: bad length\n");
            return SNMP_ERR_WRONGLENGTH;
        }
        break;

    case RESERVE2:
        size = var_val_len;
        value = *(long *) var_val;

        break;

    case FREE:
        /*
         * Release any resources that have been allocated 
         */
        break;

    case ACTION:
        /*
         * The variable has been stored in 'value' for you to use,
         * and you have just been asked to do something with it.
         * Note that anything done here must be reversable in the UNDO case
         */
        break;

    case UNDO:
        /*
         * Back out any changes made in the ACTION case 
         */
        break;

    case COMMIT:
        /*
         * Things are working well, so it's now safe to make the change
         * permanently.  Make sure that anything done here can't fail!
         */
        break;
    }
    return SNMP_ERR_NOERROR;
}


int main(int argc, char *argv[])
{
    /* change this if you want to be a SNMP master agent */
    int agentx_subagent = 1;
    /* change this if you want to run in the background */
    int background = 0;
    /* change this if you want to use syslog */
    int syslog_enable = 0;
    int snmp_pdu_max_size = -1;
    struct sigaction act;
    if (syslog_enable)
    {
      snmp_enable_calllog ();
    }
    else
    {
      snmp_enable_stderrlog ();
    }
    /* Being an agentX subAgent */
    if (agentx_subagent)
    {
      /* make us a agentX client. */
      netsnmp_ds_set_boolean (NETSNMP_DS_APPLICATION_ID, NETSNMP_DS_AGENT_ROLE,1);
    }

    /* run in background, if requested */
    if (background && netsnmp_daemonize (1, !syslog_enable))
    exit (1);

    /* Initialize TCP-IP, if NEEDED */
    SOCK_STARTUP;

    /* Master agent address */
    //netsnmp_ds_set_string (NETSNMP_DS_APPLICATION_ID, NETSNMP_DS_AGENT_X_SOCKET,
    //			 "localhost:705");/*localhost:19003 or 705*/

    /* Initialize the agent library */
    init_agent ("text");

    init_cellMgmtGroup();

    /* gsc_sub_test will be used to read gsc_sub.conf files. */
    init_snmp ("text");
    
    debug();
    
    while(1)
    {
        agent_check_and_process(1);
        sleep(1);
        debug();
    }
    
    return 0;
}