######################################################################################
#
#   File: inet_mgmt.mk
#   Time: 2019.03
#   Description: 
#   Author: Rong Tao
######################################################################################
#
#   And this file must define:
#       SRC_DIRS
#       INCLUDE_DIRS
#       SOURCES
######################################################################################

SRC_DIRS += $(INET_MGMT_ROOT)/src

INCLUDE_DIRS  += -I$(INET_MGMT_ROOT)/include

SOURCES += $(INET_MGMT_ROOT)/src/inet_mgmt.c 
SOURCES += $(INET_MGMT_ROOT)/src/inet_mgmt_socket_register.c 
